//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream AdonDamage {
            get {
                return ResourceManager.GetStream("AdonDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream AdonGolpe {
            get {
                return ResourceManager.GetStream("AdonGolpe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream BlankaDamage {
            get {
                return ResourceManager.GetStream("BlankaDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream BlankaGolpe {
            get {
                return ResourceManager.GetStream("BlankaGolpe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CammyDamage {
            get {
                return ResourceManager.GetStream("CammyDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CammyGolpe {
            get {
                return ResourceManager.GetStream("CammyGolpe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DhalsimDamage {
            get {
                return ResourceManager.GetStream("DhalsimDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DhalsimGolpe {
            get {
                return ResourceManager.GetStream("DhalsimGolpe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream J1Win {
            get {
                return ResourceManager.GetStream("J1Win", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream J2Win {
            get {
                return ResourceManager.GetStream("J2Win", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Round1 {
            get {
                return ResourceManager.GetStream("Round1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Round2 {
            get {
                return ResourceManager.GetStream("Round2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Round3 {
            get {
                return ResourceManager.GetStream("Round3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RyuDamage {
            get {
                return ResourceManager.GetStream("RyuDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RyuGolpe {
            get {
                return ResourceManager.GetStream("RyuGolpe", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SagatDamage {
            get {
                return ResourceManager.GetStream("SagatDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SagatGolpe {
            get {
                return ResourceManager.GetStream("SagatGolpe", resourceCulture);
            }
        }
        
        internal static byte[] SSF4_ABUKET {
            get {
                object obj = ResourceManager.GetObject("SSF4_ABUKET", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream TimeOver {
            get {
                return ResourceManager.GetStream("TimeOver", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ZangiefDamage {
            get {
                return ResourceManager.GetStream("ZangiefDamage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ZangiefGolpe {
            get {
                return ResourceManager.GetStream("ZangiefGolpe", resourceCulture);
            }
        }
    }
}
